### ISSUE TITLE
Dokumentációk készítése

### ISSUE THREAD

**Issue by xSinTx** [BME-MIT-IET/iet-hf-2023-uniqtest#15]
A projekt doc könyvtárába kell írni. A fájlokhoz a [Markdown](https://guides.github.com/features/mastering-markdown/) formátumot használjuk.

**Comment by zita476** [comment]
Az issue-hoz tartozó commit: docs added

**Comment by zita476** [comment]
docs added - Fixes #15

**Comment by zita476** [comment]
A dokumentációkat hozzáadtuk a docs mappához.
