### ISSUE TITLE
UI tesztek készítése - Tosca

### ISSUE THREAD

**Issue by gergo01566** [BME-MIT-IET/iet-hf-2023-uniqtest#8]
UI tesztek készítése - Tosca

**Comment by zita476** [comment]
Letöltöttem a Tosca appot, írtunk az alkalmazáshoz 8 darab tesztet.  Mindegyik automata lefut helyesen.

**Comment by gergo01566** [comment]
Szuper, nálam is lefutottak a tesztek és ugyanezt az eredményt kaptam, mehet a merge.
